name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test 1
      id: test-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 1
        setup-command: g++ lab20.cpp -o test1
        command: "./test1"
        input: "./map1.txt"
        expected-output: |-
          Peak 1 is at coordinate B4
          Peak 2 is at coordinate D2
          Peak 3 is at coordinate D6

          Valley 1 is at coordinate B3
          Valley 2 is at coordinate C4
          Valley 3 is at coordinate E3
        comparison-method: contains
        timeout: 1
        max-score: 5
    - name: Test 2
      id: test-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 2
        setup-command: g++ lab20.cpp -o test2
        command: "./test2"
        input: "./map2.txt"
        expected-output: |-
          Peak 1 is at coordinate C2
          Peak 2 is at coordinate C4
          Peak 3 is at coordinate D5
          Peak 4 is at coordinate E2

          Valley 1 is at coordinate B2
          Valley 2 is at coordinate E6
        comparison-method: contains
        timeout: 1
        max-score: 5
    - name: Test 3
      id: test-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 3
        setup-command: g++ lab20.cpp -o test3
        command: "./test3"
        input: "./map3.txt"
        expected-output: |-
          Peak 1 is at coordinate D2

          Valley 1 is at coordinate B3
        comparison-method: contains
        timeout: 1
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-1_RESULTS: "${{steps.test-1.outputs.result}}"
        TEST-2_RESULTS: "${{steps.test-2.outputs.result}}"
        TEST-3_RESULTS: "${{steps.test-3.outputs.result}}"
      with:
        runners: test-1,test-2,test-3
